name: can install and run
# a test that the program can compile, run and terminate

on:
  push:

jobs:
  can_compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: add .env file
      run: |

    - name: Install dependencies
      run: |
        npm install

    - name: can run 
      run: |
        npm start &
        sleep 5

    - name: Test if server is running
      run: |
        curl --fail http://localhost:4000 || exit 1

    - name: Stop the server
      run: pkill -f "node" || true
