name: can install, unit test, run
# a test that the program can compile, run and terminate

on:
  push:

jobs:
  can_compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: add .env file
      run: |
        echo "ATLAS_URI='mongodb+srv://cls0:BqoQvMjBEVSU3myD@cluster0.qzam1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'" > .env
        echo "ATLAS_URI='mongodb+srv://cls0:BqoQvMjBEVSU3myD@cluster0.qzam1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'" > backend/.env

    - name: Install dependencies
      run: |
        npm install
    
    - name: run unit tests
      run: |
        npm run test

    - name: can run 
      run: |
        npm start &
        sleep 5

    - name: Search for console.log statements in frontend
      run: |
        if grep -r "console\.log" ./frontend; then
          echo "❌ console.log statements found!"
          exit 1
        else
          echo "✅ No console.log statements found."
        fi

    - name: Test if server is running
      run: |
        curl --fail http://localhost:4000 || exit 1

    - name: Stop the server
      run: pkill -f "node" || true
