name: typescript can compile
# a test that the program can compile, run and terminate

on:
  push:

jobs:
  can_compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd backend/ && npm install

    - name: install typescript
      run: |
        cd backend/ && npm install -D typescript

    - name: Compile TypeScript files
      run: |
        tsc --noEmit
